"""Storyboard pages 4-5: mass ratios and volume (per-particle) ratios.

Both scenes reuse the dashed-datum row layout from `pile_to_gsd`, with the
coarsest tier on top. On the right, a brace gathers the three ratio
expressions into a vector.

Mass ratio for tier i: total retained mass on sieve i divided by the
coarsest tier's retained mass — M_i / M_1.

Volume ratio for tier i: mass of *one* coarse particle divided by *one*
tier-i particle — M(x_1) / M(x_i) = (x_1 / x_i)^3. The storyboard drew
this inverted (small over large); the paper's ζ uses large over small,
so this scene matches the paper.
"""

from __future__ import annotations

import numpy as np
from manim import (
    DOWN,
    LEFT,
    RIGHT,
    UP,
    Brace,
    Create,
    DashedLine,
    FadeIn,
    Line,
    MathTex,
    Polygon,
    Scene,
    Text,
    VGroup,
    Write,
    config,
    interpolate_color,
    WHITE,
)

from _common import (
    BACKGROUND,
    COARSE,
    COARSE_R,
    FINE,
    FINE_R,
    FOREGROUND,
    MID,
    MID_R,
    make_particle,
    particle_cluster,
    tex_text,
)

config.background_color = BACKGROUND


# Mirror pile_to_gsd so the three scenes feel continuous.
N_COARSE, N_MID, N_FINE = 8, 22, 65

ROW_YS = (2.0, 0.0, -2.0)
DATUM_X_LO, DATUM_X_HI = -6.5, 2.4


def _datum(y: float) -> DashedLine:
    return DashedLine(
        start=[DATUM_X_LO, y, 0],
        end=[DATUM_X_HI, y, 0],
        color=FOREGROUND,
        stroke_width=1.5,
        dash_length=0.12,
    )


def _slash(height: float = 0.9) -> Line:
    """Diagonal divider between numerator and denominator."""
    h = height / 2
    return Line(
        [-h * 0.55, -h, 0],
        [h * 0.55, h, 0],
        color=FOREGROUND,
        stroke_width=2.5,
    )


def mass_blob(
    radius: float,
    color,
    label: str,
    seed: int | None = None,
    n_pts: int = 96,
) -> VGroup:
    """A smooth potato-shaped blob (mechanics-of-materials style) with a math
    label inscribed.

    Shape is generated by perturbing a circle with a low-frequency Fourier
    sum (modes 2..5, small amplitudes), which gives gentle lobes instead of
    spikes. If `seed` is None, it's derived from the label so any two blobs
    sharing a label come out identical.
    """
    if seed is None:
        seed = sum(ord(c) for c in label)
    rng = np.random.default_rng(seed)

    n_modes = 4
    amps = rng.uniform(-0.07, 0.07, n_modes)
    phases = rng.uniform(0, 2 * np.pi, n_modes)

    pts = []
    for k in range(n_pts):
        theta = 2 * np.pi * k / n_pts
        deform = sum(
            amps[m] * np.cos((m + 2) * theta - phases[m]) for m in range(n_modes)
        )
        r = radius * (1.0 + deform)
        pts.append([r * np.cos(theta), r * np.sin(theta), 0.0])
    fill = interpolate_color(color, WHITE, 0.55)
    blob = Polygon(
        *pts,
        color=color,
        fill_color=fill,
        fill_opacity=1.0,
        stroke_width=2.0,
    )
    text = MathTex(label, color=color).scale(0.9 * radius / 0.6)
    text.move_to(blob.get_center())
    return VGroup(blob, text)


def _bracketed(rows: VGroup, center_x: float) -> VGroup:
    """Wrap a vertical stack of expressions in matching left/right braces."""
    rows.move_to([center_x, 0, 0])
    return VGroup(Brace(rows, LEFT), rows, Brace(rows, RIGHT))


def _row_aligned_vector(
    labels: list[MathTex],
    center_x: float,
    row_ys: tuple[float, ...],
    label_scale: float = 1.4,
    brace_pad: float = 0.6,
) -> VGroup:
    """Place each label at its corresponding row y and wrap in a brace whose
    height spans the full row range — so braces line up with the figures on
    the left and stay the same height across vectors with different inner
    geometry.
    """
    from manim import Rectangle

    for lbl, y in zip(labels, row_ys):
        lbl.scale(label_scale).move_to([center_x, y, 0])
    stack = VGroup(*labels)
    anchor = Rectangle(
        width=stack.width + 0.4,
        height=row_ys[0] - row_ys[-1] + brace_pad,
        stroke_opacity=0,
        fill_opacity=0,
    ).move_to([center_x, (row_ys[0] + row_ys[-1]) / 2, 0])
    return VGroup(Brace(anchor, LEFT), stack, Brace(anchor, RIGHT))


class MassRatios(Scene):
    """Pile of tier i ÷ pile of coarse, with the M_i/M_1 vector on the right."""

    def construct(self):
        title = tex_text("Mass Ratios", font_size=42, color=FOREGROUND).to_edge(UP, buff=0.4)

        # Numerator: a potato blob labeled with the tier's mass M_i.
        # Denominator: the same M_1 potato on every row (identical shape).
        # Sizes are uniform — the ratios live in the *labels*, not the blob area.
        blob_r = 0.7
        numerators = [
            mass_blob(blob_r, COARSE, r"M_1"),
            mass_blob(blob_r, MID, r"M_2"),
            mass_blob(blob_r, FINE, r"M_3"),
        ]
        denominators = [mass_blob(blob_r, COARSE, r"M_1") for _ in range(3)]

        rows = VGroup()
        for y, num, den in zip(ROW_YS, numerators, denominators):
            num.move_to([-5.0, y, 0])
            den.move_to([-2.0, y, 0])
            slash = _slash(height=1.3).move_to([-3.5, y, 0])
            rows.add(VGroup(num, slash, den))

        datums = VGroup(
            _datum((ROW_YS[0] + ROW_YS[1]) / 2),
            _datum((ROW_YS[1] + ROW_YS[2]) / 2),
        )

        # Vector of mass-ratio expressions, vertically aligned with the rows.
        m1 = MathTex(r"M_1/M_1").set_color(COARSE)
        m2 = MathTex(r"M_2/M_1").set_color(MID)
        m3 = MathTex(r"M_3/M_1").set_color(FINE)
        bracket = _row_aligned_vector([m1, m2, m3], center_x=4.3, row_ys=ROW_YS)

        self.play(Write(title), run_time=0.6)
        self.play(Create(datums), run_time=0.5)
        for row in rows:
            self.play(FadeIn(row, shift=DOWN * 0.1), run_time=0.55)
        self.play(
            FadeIn(bracket[0]),
            FadeIn(bracket[2]),
            Write(m1),
            Write(m2),
            Write(m3),
            run_time=1.2,
        )
        self.wait(2.05)


class VolumeRatios(Scene):
    """One coarse particle ÷ one tier-i particle = ζ_i = (x_1/x_i)^3."""

    def construct(self):
        title = tex_text("Volume Ratios", font_size=42, color=FOREGROUND).to_edge(UP, buff=0.4)

        # Numerator on every row: a single coarse particle.
        # Denominator: a single particle of the row's tier.
        tier_specs = [
            (COARSE_R, COARSE),
            (MID_R, MID),
            (FINE_R, FINE),
        ]

        rows = VGroup()
        for y, (r, color) in zip(ROW_YS, tier_specs):
            num = make_particle(COARSE_R, COARSE).move_to([-5.0, y, 0])
            den = make_particle(r, color).move_to([-2.0, y, 0])
            slash = _slash(height=1.3).move_to([-3.5, y, 0])
            rows.add(VGroup(num, slash, den))

        datums = VGroup(
            _datum((ROW_YS[0] + ROW_YS[1]) / 2),
            _datum((ROW_YS[1] + ROW_YS[2]) / 2),
        )

        # Volume-ratio entries: V_1 in the numerator on every row.
        v1 = MathTex(r"V_1/V_1").set_color(COARSE)
        v2 = MathTex(r"V_1/V_2").set_color(MID)
        v3 = MathTex(r"V_1/V_3").set_color(FINE)
        bracket = _row_aligned_vector([v1, v2, v3], center_x=4.3, row_ys=ROW_YS)

        self.play(Write(title), run_time=0.6)
        self.play(Create(datums), run_time=0.5)
        for row in rows:
            self.play(FadeIn(row, shift=DOWN * 0.1), run_time=0.55)
        self.play(
            FadeIn(bracket[0]),
            FadeIn(bracket[2]),
            Write(v1),
            Write(v2),
            Write(v3),
            run_time=1.2,
        )
        self.wait(9.0)
